### ISSUE TITLE
vue-credit-card-field dependency not found

### ISSUE THREAD

**Issue by VerzatileTom** [actengage/vue-credit-card-field#1]
How do you add this in your Vue?

I tried installing it using npm as instructed. I tried

```js
import VueCreditCardField from 'vue-credit-card-field'

export default {
  components: { VueCreditCardField  }
}
```

but webpack says 'vue-credit-card-field' not found in the dependency.

**Comment by JTorres87** [comment]
I had the same issue, it had me scratching my head.

Looks like the package.json does not include the main file definition
 "main":"./dist/vue-credit-card-field.min.js"

To use the component try the following:

```
import VueCreditCardField from 'vue-credit-card-field/dist/vue-credit-card-field.js';
require('vue-credit-card-field/dist/vue-credit-card-field.css');
Vue.use(VueCreditCardField);
```

**Comment by actengage** [comment]
Sorry for missing this thread. I didn't actually realize other people were using this library. The dist files are mainly for using it in a browser or some other legacy method. I never actually use the dist directly for components. I might need to rethink the package.json, the module property, to see if I can improve this default behavior at all. Right now for imports, I use import the vue file directly. `import CreditCardField from 'vue-credit-card-field/src/CreditCardField'`. All the packages in this Github account repo are all bundled using the boilerplate.

**Comment by actengage** [comment]
Here is a real working example from another library in this Github account. https://github.com/actengage/vue-giveworks-form/blob/master/src/Components/Gateways/AuthorizeNet/AuthorizeNetCreditCard.vue

**Comment by actengage** [comment]
Closing this thread. Re-open for new issues.

**Comment by bill-dou** [comment]
`import CreditCardField from 'vue-credit-card-field/src/Components/CreditCardField'`
It works to me!
