### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by carlganz** [actengage/vue-credit-card-field#2]
Would you be willing to accept a PR for a types file for TypeScript support. It's not my area of expertise, but I think I can figure it out.

**Comment by actengage** [comment]
Haven't had the time to incorporate TypeScript in our build, and unless its for everything we do its hard to support it for one library. That said, if it doesn't break anything if I don't use TS and you still want to add support, take a look at the latest version and add it to the new component as well. TS is something in my list but no timeframe, especially with Vue 3 being rewritten for it.
